const staticBoard = ([
  [
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 11,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 12,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 13,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 14,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 15,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 16,
    },
    {
      status: 'hidden',
      bomb: true,
      neighbours: 0,
      key: 17,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 18,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 19,
    },
  ],
  [
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 21,
    },
    {
      status: 'hidden',
      bomb: true,
      neighbours: 0,
      key: 22,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 23,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 24,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 25,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 26,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 27,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 28,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 29,
    },
  ],
  [
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 31,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 32,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 33,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 34,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 35,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 36,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 37,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 38,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 39,
    },
  ],
  [
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 41,
    },
    {
      status: 'hidden',
      bomb: true,
      neighbours: 0,
      key: 42,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 43,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 44,
    },
    {
      status: 'hidden',
      bomb: true,
      neighbours: 0,
      key: 45,
    },
    {
      status: 'hidden',
      bomb: true,
      neighbours: 0,
      key: 46,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 47,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 48,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 49,
    },
  ],
  [
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 51,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 52,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 53,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 54,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 3,
      key: 55,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 56,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 57,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 58,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 59,
    },
  ],
  [
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 61,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 62,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 63,
    },
    {
      status: 'hidden',
      bomb: true,
      neighbours: 0,
      key: 64,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 65,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 66,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 67,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 68,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 69,
    },
  ],
  [
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 71,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 72,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 73,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 74,
    },
    {
      status: 'hidden',
      bomb: true,
      neighbours: 0,
      key: 75,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 76,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 77,
    },
    {
      status: 'hidden',
      bomb: true,
      neighbours: 0,
      key: 78,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 79,
    },
  ],
  [
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 81,
    },
    {
      status: 'hidden',
      bomb: true,
      neighbours: 0,
      key: 82,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 83,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 84,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 85,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 2,
      key: 86,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 87,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 88,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 89,
    },
  ],
  [
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 91,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 92,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 93,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 94,
    },
    {
      status: 'hidden',
      bomb: true,
      neighbours: 0,
      key: 95,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 1,
      key: 96,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 97,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 98,
    },
    {
      status: 'hidden',
      bomb: false,
      neighbours: 0,
      key: 99,
    },
  ],
]);

export default staticBoard;